from django.contrib import admin
from .models import *

# Register your models here.

admin.site.register(TipoExamen)
admin.site.register(Examen)
admin.site.register(Especialidad)
admin.site.register(CIE)
admin.site.register(Provincia)
admin.site.register(Canton)
admin.site.register(Parroquia)
admin.site.register(Medico)
admin.site.register(UnidadMedica)
admin.site.register(Sucursal)
admin.site.register(Paciente)
admin.site.register(SucursalExamen)
admin.site.register(GrupoExamen)
admin.site.register(Consulta)
admin.site.register(Orden)
admin.site.register(UnidadesRecomendadas)
admin.site.register(Farmacia)
admin.site.register(Factura)
admin.site.register(OrdenFactura)
admin.site.register(Comision)
admin.site.register(Tarifa)
admin.site.register(Medicamento)
admin.site.register(MedicamentoRecetado)
admin.site.register(MedicamentoFarmacia)
admin.site.register(Antecedentes)
admin.site.register(AntecedentesObstetricos)
admin.site.register(AntecedentesPediatricos)
admin.site.register(Resultados)
admin.site.register(RatingMedico)
admin.site.register(RatingMedioDiagnostico)
admin.site.register(Actividad)
admin.site.register(Seguro)
admin.site.register(MedicoSeguro)
admin.site.register(EventosCalendario)
admin.site.register(IntervalosDisponibilidad)
admin.site.register(citasMedicas)