# Generated by Django 3.1.2 on 2020-10-31 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_auto_20201031_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('examen', models.CharField(blank=True, max_length=20, null=True)),
                ('id_tipo_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datos.tipoexamen')),
            ],
            options={
                'db_table': 'examen',
            },
        ),
    ]
