# Generated by Django 3.1.2 on 2020-10-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0003_examen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('especialidad', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'especialidad',
            },
        ),
    ]
