# Generated by Django 3.1.2 on 2020-12-01 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0007_medico_activado'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='regSene',
            field=models.FileField(null=True, upload_to='sene'),
        ),
    ]
