# Generated by Django 3.1.2 on 2020-12-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0008_medico_regsene'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='regAcess',
            field=models.FileField(null=True, upload_to='acess'),
        ),
    ]
