# Generated by Django 3.1.2 on 2020-12-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0010_auto_20201206_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='direccion_consultorio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='estudios',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='experiencia',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='referencia_consultorio',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='telefono_cita',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
