# Generated by Django 3.1.2 on 2020-12-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0011_auto_20201206_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='cod_telefono_pais',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
