# Generated by Django 3.1.2 on 2020-12-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0012_medico_cod_telefono_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='cod_telefono_pais',
            field=models.CharField(blank=True, choices=[('53', 'CUBA'), ('55', 'Brasil'), ('57', 'Colombia'), ('593', 'Ecuador')], max_length=3, null=True),
        ),
    ]
