# Generated by Django 3.1.2 on 2020-12-09 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datos', '0014_auto_20201207_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('lat', models.CharField(blank=True, max_length=10, null=True)),
                ('lon', models.CharField(blank=True, max_length=10, null=True)),
                ('slogan', models.CharField(blank=True, max_length=50, null=True)),
                ('quienes_somos', models.CharField(blank=True, max_length=250, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('direccionmatriz', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('pag_web', models.CharField(blank=True, max_length=100, null=True)),
                ('horario_atencion', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_habilitantes_folder', models.CharField(blank=True, max_length=10, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'unidad_medica',
            },
        ),
    ]
