# Generated by Django 3.1.2 on 2020-12-09 11:21

import datos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0015_unidadmedica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadmedica',
            name='doc_habilitantes_folder',
        ),
        migrations.AddField(
            model_name='unidadmedica',
            name='regArcsa',
            field=models.FileField(null=True, upload_to=datos.models.user_directory_path_arcsa),
        ),
        migrations.AddField(
            model_name='unidadmedica',
            name='regRUC',
            field=models.FileField(null=True, upload_to=datos.models.user_directory_path_ruc),
        ),
    ]
