# Generated by Django 3.1.2 on 2020-12-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0018_auto_20201209_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='especialidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
