# Generated by Django 3.1.2 on 2020-12-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0019_auto_20201209_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedica',
            name='referencia_direccion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
