# Generated by Django 3.1.2 on 2020-12-11 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0020_unidadmedica_referencia_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='especialidad',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
