# Generated by Django 3.1.2 on 2020-12-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0022_cie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cie',
            name='cie',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
