# Generated by Django 3.1.2 on 2020-12-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0023_auto_20201211_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('canton', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'canton',
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('parroquia', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'parroquia',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('provincia', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'provincia',
            },
        ),
    ]
