# Generated by Django 3.1.2 on 2020-12-11 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0024_canton_parroquia_provincia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='canton',
            old_name='codigo',
            new_name='codigo_canton',
        ),
        migrations.RenameField(
            model_name='provincia',
            old_name='codigo',
            new_name='codigo_prov',
        ),
        migrations.AddField(
            model_name='canton',
            name='provincia',
            field=models.ForeignKey(db_column='codigo_prov', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datos.provincia'),
        ),
        migrations.AddField(
            model_name='parroquia',
            name='canton',
            field=models.ForeignKey(db_column='codigo_canton', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datos.canton'),
        ),
    ]
