# Generated by Django 3.1.2 on 2020-12-11 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0025_auto_20201211_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parroquia',
            name='canton',
        ),
        migrations.DeleteModel(
            name='Canton',
        ),
        migrations.DeleteModel(
            name='Parroquia',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
    ]
