# Generated by Django 3.1.2 on 2020-12-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0026_auto_20201211_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provincia', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'provincia',
            },
        ),
    ]
