# Generated by Django 3.1.2 on 2020-12-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0030_canton'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Canton',
        ),
    ]
