# Generated by Django 3.1.2 on 2020-12-11 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0033_parroquia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Parroquia',
        ),
    ]
