# Generated by Django 3.1.2 on 2020-12-11 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0035_parroquia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parroquia',
            old_name='canto',
            new_name='canton',
        ),
    ]
