# Generated by Django 3.1.2 on 2020-12-12 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0036_auto_20201211_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parroquia',
            name='canton',
        ),
        migrations.DeleteModel(
            name='Canton',
        ),
        migrations.DeleteModel(
            name='Parroquia',
        ),
    ]
