# Generated by Django 3.1.2 on 2020-12-13 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0043_auto_20201212_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='canton2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcanton2', to='datos.canton'),
        ),
        migrations.AddField(
            model_name='medico',
            name='direccion_consultorio2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='parroquia2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parroquia2', to='datos.parroquia'),
        ),
        migrations.AddField(
            model_name='medico',
            name='provincia2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincia2', to='datos.provincia'),
        ),
        migrations.AddField(
            model_name='medico',
            name='referencia_consultorio2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='telefono_cita2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='medico',
            name='canton1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canton1', to='datos.canton'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='parroquia1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parroquia1', to='datos.parroquia'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='provincia1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincia1', to='datos.provincia'),
        ),
    ]
