# Generated by Django 3.1.2 on 2020-12-13 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0046_auto_20201212_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='canton1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canton1', to='datos.canton'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='canton2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pcanton2', to='datos.canton'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='parroquia1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parroquia1', to='datos.parroquia'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='parroquia2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parroquia2', to='datos.parroquia'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='provincia1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincia1', to='datos.provincia'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='provincia2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincia2', to='datos.provincia'),
        ),
    ]
