# Generated by Django 3.1.2 on 2020-12-13 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0047_auto_20201213_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='especialidad1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='especialidad1', to='datos.especialidad'),
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidad2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='especialidad2', to='datos.especialidad'),
        ),
        migrations.AddField(
            model_name='medico',
            name='subespecialidad1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='subespecialidad2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='telefono_whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
