# Generated by Django 3.1.2 on 2020-12-13 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0049_paciente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='parroquia1',
            new_name='parroquia',
        ),
    ]
