# Generated by Django 3.1.2 on 2020-12-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0050_auto_20201213_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_nac',
            field=models.DateField(null=True),
        ),
    ]
