# Generated by Django 3.1.2 on 2020-12-15 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0051_paciente_fecha_nac'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadmedica',
            name='ciudad',
        ),
        migrations.AddField(
            model_name='unidadmedica',
            name='canton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canton_um', to='datos.canton'),
        ),
        migrations.AddField(
            model_name='unidadmedica',
            name='parroquia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parroquia_um', to='datos.parroquia'),
        ),
        migrations.AddField(
            model_name='unidadmedica',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincia_um', to='datos.provincia'),
        ),
    ]
