# Generated by Django 3.1.2 on 2020-12-15 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0052_auto_20201214_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedica',
            name='telefono_whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
