# Generated by Django 3.1.2 on 2020-12-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0053_unidadmedica_telefono_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedica',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unidadmedica',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
