# Generated by Django 3.1.2 on 2020-12-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0054_auto_20201214_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoexamen',
            name='categoria',
            field=models.CharField(choices=[('LABORATORIO', 'LABORATORIO'), ('IMAGEN', 'IMAGEN'), ('PROCEDIMIENTO', 'PROCEDIMIENTO')], default='', max_length=20),
        ),
    ]
