# Generated by Django 3.1.2 on 2020-12-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0055_auto_20201216_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipoexamen',
            name='tipo_examen',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
