# Generated by Django 3.1.2 on 2020-12-16 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0056_auto_20201216_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examen',
            old_name='id_tipo_examen',
            new_name='tipo_examen',
        ),
    ]
