# Generated by Django 3.1.2 on 2020-12-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0057_auto_20201216_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
