# Generated by Django 3.1.2 on 2020-12-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0058_examen_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='examen',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
