# Generated by Django 3.1.2 on 2020-12-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0060_auto_20201217_0954'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CIE',
        ),
    ]
