# Generated by Django 3.1.2 on 2020-12-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0061_delete_cie'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('cie', models.CharField(blank=True, max_length=350, null=True)),
            ],
            options={
                'db_table': 'cie',
            },
        ),
    ]
