# Generated by Django 3.1.2 on 2020-12-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0062_cie'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='lat1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='lat2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='lon1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='lon2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
