# Generated by Django 3.1.2 on 2020-12-22 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0064_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='direccionmatriz',
        ),
    ]
