# Generated by Django 3.1.2 on 2020-12-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0066_remove_unidadmedica_direccionmatriz'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedica',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unidadmedica',
            name='razon_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unidadmedica',
            name='ruc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
