# Generated by Django 3.1.2 on 2020-12-22 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0067_auto_20201222_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='unidadMedica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datos.unidadmedica'),
        ),
    ]
