# Generated by Django 3.1.2 on 2020-12-28 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0068_sucursal_unidadmedica'),
    ]

    operations = [
        migrations.CreateModel(
            name='SucursalExamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('examen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos.examen')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos.sucursal')),
            ],
            options={
                'db_table': 'sucursal_examen',
            },
        ),
    ]
