# Generated by Django 3.1.2 on 2020-12-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0069_sucursalexamen'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursalexamen',
            name='entrega',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sucursalexamen',
            name='preparacion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='sucursalexamen',
            name='referencia',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
