# Generated by Django 3.1.2 on 2021-01-01 14:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0072_grupoexamen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='FechaConsulta')),
                ('id_diagnostico', models.ForeignKey(db_column='id_diagnostico', on_delete=django.db.models.deletion.DO_NOTHING, to='datos.cie')),
                ('id_medico', models.ForeignKey(db_column='id_medico', on_delete=django.db.models.deletion.DO_NOTHING, to='datos.medico')),
                ('id_paciente', models.ForeignKey(db_column='id_paciente', on_delete=django.db.models.deletion.DO_NOTHING, to='datos.paciente')),
            ],
            options={
                'db_table': 'consulta',
            },
        ),
    ]
