# Generated by Django 3.1.2 on 2021-01-01 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0074_auto_20210101_0917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consulta',
            old_name='id_consulta',
            new_name='id',
        ),
    ]
