# Generated by Django 3.1.2 on 2021-01-05 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0076_paciente_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.ForeignKey(db_column='id_consulta', on_delete=django.db.models.deletion.DO_NOTHING, to='datos.consulta')),
                ('examen', models.ForeignKey(db_column='id_examen', on_delete=django.db.models.deletion.DO_NOTHING, to='datos.examen')),
            ],
            options={
                'db_table': 'orden',
            },
        ),
    ]
