# Generated by Django 3.1.2 on 2021-01-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0078_auto_20210105_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='historia_clinica',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
