# Generated by Django 3.1.2 on 2021-01-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0079_auto_20210106_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='historia_enfermedad',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='motivo_consulta',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
