# Generated by Django 3.1.2 on 2021-01-06 18:05

import datos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0080_auto_20210106_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.FileField(null=True, upload_to=datos.models.user_directory_path_foto_paciente),
        ),
    ]
