# Generated by Django 3.1.2 on 2021-01-09 14:01

import datos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0083_auto_20210108_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='regArcsa',
            field=models.FileField(null=True, upload_to=datos.models.user_directory_path_arcsa),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='regRUC',
            field=models.FileField(null=True, upload_to=datos.models.user_directory_path_ruc),
        ),
        migrations.AlterField(
            model_name='unidadmedica',
            name='regArcsa',
            field=models.FileField(null=True, upload_to=datos.models.user_directory_path_arcsa),
        ),
        migrations.AlterField(
            model_name='unidadmedica',
            name='regRUC',
            field=models.FileField(null=True, upload_to=datos.models.user_directory_path_ruc),
        ),
    ]
