# Generated by Django 3.1.2 on 2021-01-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0084_auto_20210109_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='razon_social',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmacia',
            name='ruc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
