# Generated by Django 3.1.2 on 2021-01-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0085_auto_20210109_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='tipo_generico',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='via_aplicacion',
            field=models.CharField(choices=[('ORAL', 'ORAL'), ('ORAL', 'ORAL'), ('SUBLINGUAL', 'SUBLINGUAL'), ('INTRAVENOSO', 'INTRAVENOSO'), ('INTRAMUSCULAR', 'INTRAMUSCULAR'), ('SUBCUTANEA', 'SUBCUTANEA'), ('INHALACION', 'INHALACION'), ('INTRANASAL', 'INTRANASAL'), ('TOPICO', 'TOPICO'), ('TRANSDERMICA', 'TRANSDERMICA')], default='', max_length=50),
        ),
    ]
