# Generated by Django 3.1.2 on 2021-01-10 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0087_medicamentorecetado'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicamentorecetado',
            table='medicamento_recetado',
        ),
    ]
