# Generated by Django 3.1.2 on 2021-01-13 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0089_consulta_tipo_diagnostico'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicamentoFarmacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmacia', models.ForeignKey(db_column='id_farmacia', on_delete=django.db.models.deletion.DO_NOTHING, to='datos.farmacia')),
                ('medicamento', models.ForeignKey(db_column='id_medicamento', on_delete=django.db.models.deletion.DO_NOTHING, to='datos.medicamento')),
            ],
        ),
    ]
