# Generated by Django 3.1.2 on 2021-01-13 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0090_medicamentofarmacia'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medicamentofarmacia',
            table='medicamento_farmacia',
        ),
    ]
