# Generated by Django 3.1.2 on 2021-01-19 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0092_auto_20210115_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentorecetado',
            name='farmacia',
            field=models.ForeignKey(blank=True, db_column='id_farmacia', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datos.farmacia'),
        ),
    ]
