# Generated by Django 3.1.2 on 2021-01-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0093_medicamentorecetado_farmacia'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentorecetado',
            name='precio_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
