# Generated by Django 3.1.2 on 2021-01-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0095_auto_20210119_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='precio_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
