# Generated by Django 3.1.2 on 2021-01-21 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0098_remove_orden_recomendacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadesRecomendadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GRUPO', 'GRUPO'), ('SUCURSAL', 'SUCURSAL')], default='', max_length=50)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos.unidadmedica')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos.sucursal')),
            ],
        ),
    ]
