# Generated by Django 3.1.2 on 2021-01-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0099_unidadesrecomendadas'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='unidadesrecomendadas',
            table='unidades_recomendadas',
        ),
    ]
