# Generated by Django 3.1.2 on 2021-01-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0101_unidadesrecomendadas_consulta'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
