# Generated by Django 3.1.2 on 2021-01-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0102_medico_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicamentorecetado',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='medicamentorecetado',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='medicamentorecetado',
            name='frecuencia',
        ),
        migrations.AddField(
            model_name='medicamentorecetado',
            name='indicaciones',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
