# Generated by Django 3.1.2 on 2021-01-27 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0103_auto_20210125_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Antecedentes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PERSONAL', 'PERSONAL'), ('FAMILIAR', 'FAMILIAR')], default='', max_length=50)),
                ('consulta', models.ForeignKey(db_column='id_consulta', on_delete=django.db.models.deletion.DO_NOTHING, to='datos.consulta')),
                ('diagnostico', models.ForeignKey(db_column='id_diagnostico', on_delete=django.db.models.deletion.DO_NOTHING, to='datos.cie')),
            ],
            options={
                'db_table': 'antecedentes',
            },
        ),
    ]
