# Generated by Django 3.1.2 on 2021-01-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0104_antecedentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamentorecetado',
            name='estado',
            field=models.CharField(choices=[('VENDIDO', 'VENDIDO'), ('INDICADO', 'INDICADO')], default='INDICADO', max_length=15),
        ),
    ]
