# Generated by Django 3.1.2 on 2021-01-30 17:27

import datos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0106_orden_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultadosFile', models.FileField(null=True, upload_to=datos.models.user_directory_path_resultados)),
            ],
            options={
                'db_table': 'resultados',
            },
        ),
    ]
