# Generated by Django 3.1.2 on 2021-02-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0108_resultados_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='precio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
