# Generated by Django 3.1.2 on 2021-02-02 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0110_antecedentesobstetricos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultados',
            name='orden',
        ),
        migrations.AddField(
            model_name='resultados',
            name='consulta',
            field=models.ForeignKey(blank=True, db_column='id_consulta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datos.consulta'),
        ),
    ]
