# Generated by Django 3.1.2 on 2021-02-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0111_auto_20210202_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='estado',
        ),
        migrations.AddField(
            model_name='consulta',
            name='estado',
            field=models.CharField(choices=[('RESULTADOS', 'RESULTADOS'), ('INDICADO', 'INDICADO')], default='INDICADO', max_length=15),
        ),
    ]
