# Generated by Django 3.1.2 on 2021-02-03 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0112_auto_20210202_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.ForeignKey(blank=True, db_column='id_medico', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datos.medico')),
                ('paciente', models.ForeignKey(blank=True, db_column='id_paciente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datos.paciente')),
            ],
            options={
                'db_table': 'rating_medico',
            },
        ),
    ]
