# Generated by Django 3.1.2 on 2021-02-03 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0113_ratingmedico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingmedico',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
