# Generated by Django 3.1.2 on 2021-02-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0114_ratingmedico_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingmedico',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
