# Generated by Django 3.1.2 on 2021-02-03 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0115_auto_20210203_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingmedico',
            name='consulta',
            field=models.ForeignKey(blank=True, db_column='id_consulta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datos.consulta'),
        ),
    ]
