# Generated by Django 3.1.2 on 2021-02-04 14:44

import datos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0117_auto_20210203_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='foto',
            field=models.FileField(null=True, upload_to=datos.models.user_directory_path_foto_medico),
        ),
    ]
