# Generated by Django 3.1.2 on 2021-02-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0118_medico_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='cod_telefono_pais',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
