# Generated by Django 3.1.2 on 2021-02-05 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0119_auto_20210204_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingMedioDiagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('GRUPO', 'GRUPO'), ('SUCURSAL', 'SUCURSAL')], default='', max_length=50)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('consulta', models.ForeignKey(blank=True, db_column='id_consulta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datos.consulta')),
                ('grupo', models.ForeignKey(blank=True, db_column='id_grupo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datos.unidadmedica')),
                ('paciente', models.ForeignKey(blank=True, db_column='id_paciente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datos.paciente')),
                ('sucursal', models.ForeignKey(blank=True, db_column='id_sucursal', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datos.sucursal')),
            ],
            options={
                'db_table': 'rating_medio_diagnostico',
            },
        ),
    ]
