# Generated by Django 3.1.2 on 2021-02-07 13:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0120_ratingmediodiagnostico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoActividad', models.CharField(choices=[('CONSULTA', 'CONSULTA'), ('SELECCION_FARMACIA', 'SELECCION_FARMACIA'), ('SELECCION_UM', 'SELECCION_UM'), ('VENTA_MEDICAMENTO', 'VENTA_MEDICAMENTO'), ('RESULTADOS', 'RESULTADOS')], default='', max_length=50)),
                ('idReferencia', models.IntegerField(blank=True, default=0, null=True)),
                ('idEntidad', models.IntegerField(blank=True, default=0, null=True)),
                ('tipoEntidad', models.CharField(choices=[('GRUPO', 'GRUPO'), ('SUCURSAL', ' SUCURSAL'), ('FARMACIA', 'FARMACIA')], default='', max_length=50)),
                ('nombreEntidad', models.CharField(blank=True, max_length=100, null=True)),
                ('fechaHora', models.DateTimeField(blank=True, db_column='fecha_actividad', default=datetime.datetime.now)),
                ('paciente', models.ForeignKey(blank=True, db_column='id_paciente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datos.paciente')),
            ],
        ),
    ]
