# Generated by Django 3.1.2 on 2021-02-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0121_actividad'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='actividad',
            table='actividad',
        ),
    ]
