# Generated by Django 3.1.2 on 2021-02-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0122_auto_20210207_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tipoEntidad',
            field=models.CharField(blank=True, choices=[('GRUPO', 'GRUPO'), ('SUCURSAL', ' SUCURSAL'), ('FARMACIA', 'FARMACIA')], default='', max_length=50, null=True),
        ),
    ]
