# Generated by Django 3.1.2 on 2021-02-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0123_auto_20210207_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fechaHora',
            field=models.DateTimeField(auto_now_add=True, db_column='fecha_actividad'),
        ),
    ]
