# Generated by Django 3.1.2 on 2021-02-07 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0124_auto_20210207_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='idReferencia',
        ),
        migrations.AddField(
            model_name='actividad',
            name='idConsulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos.consulta'),
        ),
    ]
