# Generated by Django 3.1.2 on 2021-02-07 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0125_auto_20210207_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='idEntidad',
            new_name='entidad',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='idConsulta',
        ),
        migrations.AddField(
            model_name='actividad',
            name='consulta',
            field=models.ForeignKey(blank=True, db_column='id_consulta', null=True, on_delete=django.db.models.deletion.CASCADE, to='datos.consulta'),
        ),
    ]
