# Generated by Django 3.1.2 on 2021-02-11 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0126_auto_20210207_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedentesPediatricos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentePrenatal', models.CharField(blank=True, max_length=500, null=True)),
                ('antecedenteNatal', models.CharField(blank=True, max_length=500, null=True)),
                ('antecedentePostnatal', models.CharField(blank=True, max_length=500, null=True)),
                ('consulta', models.ForeignKey(db_column='id_consulta', on_delete=django.db.models.deletion.DO_NOTHING, to='datos.consulta')),
            ],
            options={
                'db_table': 'antecedentes_pediatricos',
            },
        ),
    ]
