# Generated by Django 3.1.2 on 2021-02-11 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0128_consulta_examenclinico'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='paciente',
            field=models.IntegerField(blank=True, db_column='id_representante', null=True),
        ),
    ]
