# Generated by Django 3.1.2 on 2021-02-12 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0129_paciente_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='paciente',
        ),
        migrations.AddField(
            model_name='paciente',
            name='representante',
            field=models.ForeignKey(blank=True, db_column='id_paciente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datos.paciente'),
        ),
    ]
