# Generated by Django 3.1.2 on 2021-02-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0131_auto_20210211_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='seguro',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
