# Generated by Django 3.1.2 on 2021-02-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0132_medico_seguro'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='compensacion',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
