# Generated by Django 3.1.2 on 2021-02-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0134_auto_20210219_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedica',
            name='compensacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
