# Generated by Django 3.1.2 on 2021-02-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0135_unidadmedica_compensacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='precio_unitario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
