# Generated by Django 3.1.2 on 2021-02-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0137_resultados_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguro', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'seguro',
            },
        ),
    ]
