# Generated by Django 3.1.2 on 2021-02-25 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0138_seguro'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicoSeguro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.ForeignKey(blank=True, db_column='id_profesional', null=True, on_delete=django.db.models.deletion.CASCADE, to='datos.medico')),
                ('seguro', models.ForeignKey(blank=True, db_column='id_seguro', null=True, on_delete=django.db.models.deletion.CASCADE, to='datos.seguro')),
            ],
            options={
                'db_table': 'medico_seguro',
            },
        ),
    ]
