# Generated by Django 3.1.2 on 2021-05-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0140_eventoscalendario'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoscalendario',
            name='motivo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
