# Generated by Django 3.1.2 on 2021-05-22 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0141_eventoscalendario_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventoscalendario',
            name='doctor',
            field=models.ForeignKey(blank=True, db_column='id_profesional', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datos.medico'),
        ),
        migrations.AddField(
            model_name='eventoscalendario',
            name='mes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
