# Generated by Django 3.1.2 on 2021-05-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0145_auto_20210522_1226'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='eventoscalendario',
            table='evento_calendario',
        ),
    ]
