# Generated by Django 3.1.2 on 2021-05-22 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0146_auto_20210522_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventoscalendario',
            name='mes',
        ),
    ]
