# Generated by Django 3.1.2 on 2021-05-22 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0147_remove_eventoscalendario_mes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventoscalendario',
            old_name='doctor',
            new_name='medico',
        ),
    ]
