# Generated by Django 3.1.2 on 2021-05-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0148_auto_20210522_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='duracion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='genero',
            field=models.CharField(choices=[('MASCULINO', 'MASCULINO'), ('FEMENINO', 'FEMENINO')], default='', max_length=10),
        ),
    ]
