# Generated by Django 3.1.2 on 2021-06-16 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0150_disponibilidadcitas'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='disponibilidadcitas',
            table='disponibilidad_citas',
        ),
        migrations.CreateModel(
            name='citasMedicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.TimeField(blank=True, null=True)),
                ('fin', models.TimeField(blank=True, null=True)),
                ('duracion', models.IntegerField(default='', null=True)),
                ('fechaCita', models.DateTimeField(default='', null=True)),
                ('consulta', models.ForeignKey(blank=True, db_column='id_consulta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datos.consulta')),
                ('intervalo_disponibilidad', models.ForeignKey(blank=True, db_column='id_intervalo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datos.disponibilidadcitas')),
                ('medico', models.ForeignKey(db_column='id_medico', on_delete=django.db.models.deletion.DO_NOTHING, to='datos.medico')),
                ('paciente', models.ForeignKey(blank=True, db_column='id_paciente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='datos.paciente')),
            ],
            options={
                'db_table': 'citas_medicas',
            },
        ),
    ]
