# Generated by Django 3.1.2 on 2021-06-16 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0151_auto_20210616_1847'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisponibilidadCitas',
            new_name='IntervalosDisponibilidad',
        ),
    ]
