# Generated by Django 3.1.2 on 2021-06-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0153_auto_20210616_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='citasmedicas',
            name='estado',
            field=models.CharField(blank=True, choices=[('AGENDADO', 'AGENDADO'), ('REALIZADO', 'REALIZADO'), ('CANCELADO', 'CANCELADO')], default='', max_length=50, null=True),
        ),
    ]
