# Generated by Django 3.1.2 on 2021-06-17 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0154_citasmedicas_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citasmedicas',
            old_name='fechaCita',
            new_name='fecha_cita',
        ),
        migrations.RenameField(
            model_name='intervalosdisponibilidad',
            old_name='diaSemana',
            new_name='dia_semana',
        ),
        migrations.RenameField(
            model_name='intervalosdisponibilidad',
            old_name='fechaActualizacion',
            new_name='fecha_actualizacion',
        ),
    ]
