# Generated by Django 3.1.2 on 2021-06-17 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0155_auto_20210616_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervalosdisponibilidad',
            name='fecha_actualizacion',
        ),
    ]
