# Generated by Django 3.1.2 on 2021-06-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0157_remove_intervalosdisponibilidad_fecha_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervalosdisponibilidad',
            name='activo',
            field=models.BooleanField(default='', null=True),
        ),
    ]
