# Generated by Django 3.1.2 on 2022-03-10 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0159_citasmedicas_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('comision_total', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('LIQUIDADA', 'LIQUIDADA'), ('FUERA_DE_TERMINO', 'FUERA_DE_TERMINO'), ('CANCELADA', 'CANCELADA')], default='', max_length=50)),
                ('fecha_creacion', models.DateField(auto_now_add=True, db_column='fecha_creacion', null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, db_column='fecha_vencimiento', null=True)),
            ],
            options={
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('tipo_entidad', models.CharField(choices=[('GRUPO', 'GRUPO'), ('SUCURSAL', ' SUCURSAL'), ('FARMACIA', 'FARMACIA')], default='', max_length=50)),
                ('valor', models.FloatField(blank=True, null=True)),
                ('profesional', models.FloatField(blank=True, null=True)),
                ('hallmed', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tarifa',
            },
        ),
        migrations.AlterField(
            model_name='orden',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='OrdenFactura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('GRUPO', 'GRUPO'), ('SUCURSAL', ' SUCURSAL'), ('FARMACIA', 'FARMACIA')], default='', max_length=50)),
                ('precio_total', models.FloatField(blank=True, null=True)),
                ('comision', models.FloatField(blank=True, null=True)),
                ('farmacia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos.farmacia')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos.unidadmedica')),
                ('orden', models.ForeignKey(db_column='id_orden', on_delete=django.db.models.deletion.DO_NOTHING, to='datos.orden')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos.sucursal')),
            ],
            options={
                'db_table': 'orden_factura',
            },
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cobrado', models.FloatField(blank=True, null=True)),
                ('fecha_cobro', models.DateField(auto_now_add=True, db_column='fecha_creacion', null=True)),
                ('factura', models.ForeignKey(db_column='id_factura', on_delete=django.db.models.deletion.DO_NOTHING, to='datos.factura')),
            ],
            options={
                'db_table': 'comision',
            },
        ),
    ]
