# Generated by Django 3.1.2 on 2022-03-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0160_auto_20220309_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='antecedentes',
            options={'verbose_name_plural': 'Antecedentes'},
        ),
        migrations.AlterModelOptions(
            name='antecedentesobstetricos',
            options={'verbose_name_plural': 'Antecedentes Obstétricos'},
        ),
        migrations.AlterModelOptions(
            name='antecedentespediatricos',
            options={'verbose_name_plural': 'Antecedentes Pediátricos'},
        ),
        migrations.AlterModelOptions(
            name='canton',
            options={'verbose_name_plural': 'Cantones'},
        ),
        migrations.AlterModelOptions(
            name='cie',
            options={'verbose_name_plural': 'CIE'},
        ),
        migrations.AlterModelOptions(
            name='citasmedicas',
            options={'verbose_name_plural': 'Citas Médicas'},
        ),
        migrations.AlterModelOptions(
            name='comision',
            options={'verbose_name_plural': 'Comisiones'},
        ),
        migrations.AlterModelOptions(
            name='consulta',
            options={'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='eventoscalendario',
            options={'verbose_name_plural': 'Eventos de Calendario'},
        ),
        migrations.AlterModelOptions(
            name='examen',
            options={'verbose_name_plural': 'Exámenes'},
        ),
        migrations.AlterModelOptions(
            name='farmacia',
            options={'verbose_name_plural': 'Farmacias'},
        ),
        migrations.AlterModelOptions(
            name='grupoexamen',
            options={'verbose_name_plural': 'Exámenes - Grupos'},
        ),
        migrations.AlterModelOptions(
            name='intervalosdisponibilidad',
            options={'verbose_name_plural': 'Intervalos de Disponibilidad'},
        ),
        migrations.AlterModelOptions(
            name='medicamentofarmacia',
            options={'verbose_name_plural': 'Medicamentos - Farmacias'},
        ),
        migrations.AlterModelOptions(
            name='medicamentorecetado',
            options={'verbose_name_plural': 'Medicamentos Recetados'},
        ),
        migrations.AlterModelOptions(
            name='medico',
            options={'verbose_name_plural': 'Médicos'},
        ),
        migrations.AlterModelOptions(
            name='medicoseguro',
            options={'verbose_name_plural': 'Seguro Médico'},
        ),
        migrations.AlterModelOptions(
            name='orden',
            options={'verbose_name_plural': 'Órdenes'},
        ),
        migrations.AlterModelOptions(
            name='ordenfactura',
            options={'verbose_name_plural': 'Órdenes - Facturas'},
        ),
        migrations.AlterModelOptions(
            name='ratingmedico',
            options={'verbose_name_plural': 'Rating - Médico'},
        ),
        migrations.AlterModelOptions(
            name='ratingmediodiagnostico',
            options={'verbose_name_plural': 'Rating - Medio Diagnóstico'},
        ),
        migrations.AlterModelOptions(
            name='resultados',
            options={'verbose_name_plural': 'Resultados'},
        ),
        migrations.AlterModelOptions(
            name='seguro',
            options={'verbose_name_plural': 'Seguros'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterModelOptions(
            name='sucursalexamen',
            options={'verbose_name_plural': 'Exámenes - Sucursales'},
        ),
        migrations.AlterModelOptions(
            name='tipoexamen',
            options={'verbose_name': 'Tipo de Examen', 'verbose_name_plural': 'Tipos de Exámenes'},
        ),
        migrations.AlterModelOptions(
            name='unidadesrecomendadas',
            options={'verbose_name_plural': 'Unidades Recomendadas'},
        ),
        migrations.AlterModelOptions(
            name='unidadmedica',
            options={'verbose_name_plural': 'Unidades Médicas'},
        ),
        migrations.RenameField(
            model_name='comision',
            old_name='fecha_cobro',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='comision',
            old_name='cobrado',
            new_name='puntos',
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='comision_total',
            new_name='puntos',
        ),
        migrations.RenameField(
            model_name='ordenfactura',
            old_name='comision',
            new_name='puntos',
        ),
        migrations.RenameField(
            model_name='tarifa',
            old_name='valor',
            new_name='porcentaje',
        ),
        migrations.RemoveField(
            model_name='ordenfactura',
            name='precio_total',
        ),
        migrations.AlterField(
            model_name='comision',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ordenfactura',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
