# Generated by Django 3.2.3 on 2022-03-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0161_auto_20220313_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='compensacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
