# Generated by Django 3.1.2 on 2022-07-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0162_farmacia_compensacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='precio',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
